server:
  port: 4090

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

spring:
  application:
    name: prl-wa-task-configuration
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
